/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultiSigWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addOwner"
      | "changeRequirement"
      | "confirmTransaction"
      | "confirmations"
      | "executeTransaction"
      | "getOwners"
      | "getTransactionCount"
      | "isOwner"
      | "owners"
      | "removeOwner"
      | "required"
      | "revokeConfirmation"
      | "submitTransaction"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Confirmation"
      | "Deposit"
      | "ExecutionFailure"
      | "ExecutionSuccess"
      | "OwnerAdded"
      | "OwnerRemoved"
      | "RequirementChanged"
      | "Revocation"
      | "Submission"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeRequirement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmations",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getOwners", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "owners",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "required", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeConfirmation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTransaction",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "required", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace ConfirmationEvent {
  export type InputTuple = [owner: AddressLike, transactionId: BigNumberish];
  export type OutputTuple = [owner: string, transactionId: bigint];
  export interface OutputObject {
    owner: string;
    transactionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    sender: AddressLike,
    amount: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [sender: string, amount: bigint, balance: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionFailureEvent {
  export type InputTuple = [transactionId: BigNumberish];
  export type OutputTuple = [transactionId: bigint];
  export interface OutputObject {
    transactionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionSuccessEvent {
  export type InputTuple = [transactionId: BigNumberish];
  export type OutputTuple = [transactionId: bigint];
  export interface OutputObject {
    transactionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerAddedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnerRemovedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequirementChangedEvent {
  export type InputTuple = [required: BigNumberish];
  export type OutputTuple = [required: bigint];
  export interface OutputObject {
    required: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevocationEvent {
  export type InputTuple = [owner: AddressLike, transactionId: BigNumberish];
  export type OutputTuple = [owner: string, transactionId: bigint];
  export interface OutputObject {
    owner: string;
    transactionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionEvent {
  export type InputTuple = [transactionId: BigNumberish];
  export type OutputTuple = [transactionId: bigint];
  export interface OutputObject {
    transactionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSigWallet extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSigWallet;
  waitForDeployment(): Promise<this>;

  interface: MultiSigWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addOwner: TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;

  changeRequirement: TypedContractMethod<
    [_required: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmTransaction: TypedContractMethod<
    [_transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmations: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  executeTransaction: TypedContractMethod<
    [_transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOwners: TypedContractMethod<[], [string[]], "view">;

  getTransactionCount: TypedContractMethod<[], [bigint], "view">;

  isOwner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owners: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  removeOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  required: TypedContractMethod<[], [bigint], "view">;

  revokeConfirmation: TypedContractMethod<
    [_transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitTransaction: TypedContractMethod<
    [_destination: AddressLike, _value: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        destination: string;
        value: bigint;
        data: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addOwner"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeRequirement"
  ): TypedContractMethod<[_required: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmTransaction"
  ): TypedContractMethod<[_transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<[_transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOwners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransactionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isOwner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owners"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "required"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeConfirmation"
  ): TypedContractMethod<[_transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTransaction"
  ): TypedContractMethod<
    [_destination: AddressLike, _value: BigNumberish, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        destination: string;
        value: bigint;
        data: string;
        executed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Confirmation"
  ): TypedContractEvent<
    ConfirmationEvent.InputTuple,
    ConfirmationEvent.OutputTuple,
    ConfirmationEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionFailure"
  ): TypedContractEvent<
    ExecutionFailureEvent.InputTuple,
    ExecutionFailureEvent.OutputTuple,
    ExecutionFailureEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionSuccess"
  ): TypedContractEvent<
    ExecutionSuccessEvent.InputTuple,
    ExecutionSuccessEvent.OutputTuple,
    ExecutionSuccessEvent.OutputObject
  >;
  getEvent(
    key: "OwnerAdded"
  ): TypedContractEvent<
    OwnerAddedEvent.InputTuple,
    OwnerAddedEvent.OutputTuple,
    OwnerAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnerRemoved"
  ): TypedContractEvent<
    OwnerRemovedEvent.InputTuple,
    OwnerRemovedEvent.OutputTuple,
    OwnerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RequirementChanged"
  ): TypedContractEvent<
    RequirementChangedEvent.InputTuple,
    RequirementChangedEvent.OutputTuple,
    RequirementChangedEvent.OutputObject
  >;
  getEvent(
    key: "Revocation"
  ): TypedContractEvent<
    RevocationEvent.InputTuple,
    RevocationEvent.OutputTuple,
    RevocationEvent.OutputObject
  >;
  getEvent(
    key: "Submission"
  ): TypedContractEvent<
    SubmissionEvent.InputTuple,
    SubmissionEvent.OutputTuple,
    SubmissionEvent.OutputObject
  >;

  filters: {
    "Confirmation(address,uint256)": TypedContractEvent<
      ConfirmationEvent.InputTuple,
      ConfirmationEvent.OutputTuple,
      ConfirmationEvent.OutputObject
    >;
    Confirmation: TypedContractEvent<
      ConfirmationEvent.InputTuple,
      ConfirmationEvent.OutputTuple,
      ConfirmationEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ExecutionFailure(uint256)": TypedContractEvent<
      ExecutionFailureEvent.InputTuple,
      ExecutionFailureEvent.OutputTuple,
      ExecutionFailureEvent.OutputObject
    >;
    ExecutionFailure: TypedContractEvent<
      ExecutionFailureEvent.InputTuple,
      ExecutionFailureEvent.OutputTuple,
      ExecutionFailureEvent.OutputObject
    >;

    "ExecutionSuccess(uint256)": TypedContractEvent<
      ExecutionSuccessEvent.InputTuple,
      ExecutionSuccessEvent.OutputTuple,
      ExecutionSuccessEvent.OutputObject
    >;
    ExecutionSuccess: TypedContractEvent<
      ExecutionSuccessEvent.InputTuple,
      ExecutionSuccessEvent.OutputTuple,
      ExecutionSuccessEvent.OutputObject
    >;

    "OwnerAdded(address)": TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;
    OwnerAdded: TypedContractEvent<
      OwnerAddedEvent.InputTuple,
      OwnerAddedEvent.OutputTuple,
      OwnerAddedEvent.OutputObject
    >;

    "OwnerRemoved(address)": TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;
    OwnerRemoved: TypedContractEvent<
      OwnerRemovedEvent.InputTuple,
      OwnerRemovedEvent.OutputTuple,
      OwnerRemovedEvent.OutputObject
    >;

    "RequirementChanged(uint256)": TypedContractEvent<
      RequirementChangedEvent.InputTuple,
      RequirementChangedEvent.OutputTuple,
      RequirementChangedEvent.OutputObject
    >;
    RequirementChanged: TypedContractEvent<
      RequirementChangedEvent.InputTuple,
      RequirementChangedEvent.OutputTuple,
      RequirementChangedEvent.OutputObject
    >;

    "Revocation(address,uint256)": TypedContractEvent<
      RevocationEvent.InputTuple,
      RevocationEvent.OutputTuple,
      RevocationEvent.OutputObject
    >;
    Revocation: TypedContractEvent<
      RevocationEvent.InputTuple,
      RevocationEvent.OutputTuple,
      RevocationEvent.OutputObject
    >;

    "Submission(uint256)": TypedContractEvent<
      SubmissionEvent.InputTuple,
      SubmissionEvent.OutputTuple,
      SubmissionEvent.OutputObject
    >;
    Submission: TypedContractEvent<
      SubmissionEvent.InputTuple,
      SubmissionEvent.OutputTuple,
      SubmissionEvent.OutputObject
    >;
  };
}
